/**
 * @fileoverview Absolute Zero capsule contract.
 */

import { getDefaultAbsoluteZeroEnvironment } from '../config/absolute-zero-environments.js';

export const ABSOLUTE_ZERO_VFS_WRITABLE_ROOTS = Object.freeze([
  '/kernel',
  '/tools',
  '/.memory',
  '/artifacts'
]);

export const ABSOLUTE_ZERO_OPFS_WRITABLE_ROOTS = Object.freeze([
  '/artifacts'
]);

export const ABSOLUTE_ZERO_HOST_ROOT = '/host';

export const ABSOLUTE_ZERO_PROTECTED_PATHS = Object.freeze([
  '/.system/goal.txt',
  '/.system/environment.txt',
  '/.system/self.json'
]);

export const ABSOLUTE_ZERO_SELF_SOURCE_MIRRORS = Object.freeze([
  { webPath: '/src/capsule/runtime.js', vfsPath: '/kernel/runtime.js' },
  { webPath: '/src/capsule/contract.js', vfsPath: '/kernel/contract.js' },
  { webPath: '/src/config/absolute-zero-environments.js', vfsPath: '/kernel/environment-templates.js' }
]);

export const ABSOLUTE_ZERO_HOST_SOURCE_MIRRORS = Object.freeze([
  { webPath: '/src/entry/start-app.js', vfsPath: '/host/entry/start-app.js' },
  { webPath: '/src/entry/seed-vfs.js', vfsPath: '/host/entry/seed-vfs.js' },
  { webPath: '/src/capsule/host.js', vfsPath: '/host/capsule/host.js' },
  { webPath: '/src/core/llm-client.js', vfsPath: '/host/core/llm-client.js' },
  { webPath: '/src/core/provider-registry.js', vfsPath: '/host/core/provider-registry.js' },
  { webPath: '/src/core/vfs-module-loader.js', vfsPath: '/host/core/vfs-module-loader.js' },
  { webPath: '/src/boot-helpers/vfs-bootstrap.js', vfsPath: '/host/boot-helpers/vfs-bootstrap.js' },
  { webPath: '/src/infrastructure/stream-parser.js', vfsPath: '/host/infrastructure/stream-parser.js' },
  { webPath: '/src/ui/capsule/index.js', vfsPath: '/host/ui/capsule/index.js' }
]);

export function buildAbsoluteZeroSelfManifest(options = {}) {
  const includeHostWithinSelf = !!options.includeHostWithinSelf;
  return {
    mode: 'absolute_zero',
    goalPath: '/.system/goal.txt',
    environmentPath: '/.system/environment.txt',
    hostIncluded: includeHostWithinSelf,
    stores: {
      vfs: 'Normal text and code files.',
      opfs: 'Large blobs and binary artifacts.'
    },
    visibleTools: ['ReadFile', 'WriteFile', 'LoadModule'],
    rules: [
      'Your durable memory is whatever you write.',
      'Do not assume browser APIs exist until you verify them.',
      'Prefer small reversible changes.',
      'Batch independent tool calls when helpful.'
    ],
    llmContext: {
      mode: 'autonomous',
      hiddenSystemPrompt: false,
      bootstrapMessages: ['Goal', 'Environment', 'Self'],
      apiRoles: {
        assistant: 'Generated by the model.',
        user: 'Host-injected observations such as bootstrap files, tool results, and host notices.'
      }
    },
    sourceRoots: [
      '/.system',
      '/kernel',
      '/tools',
      '/.memory',
      '/artifacts',
      ...(includeHostWithinSelf ? [ABSOLUTE_ZERO_HOST_ROOT] : [])
    ],
    writableRoots: [
      ...ABSOLUTE_ZERO_VFS_WRITABLE_ROOTS,
      'opfs:/artifacts',
      ...(includeHostWithinSelf ? [ABSOLUTE_ZERO_HOST_ROOT] : [])
    ],
    protectedPaths: ABSOLUTE_ZERO_PROTECTED_PATHS,
    loadModule: {
      path: 'Any VFS .js path under /tools or /kernel',
      effect: 'Loads a module and registers callable tool exports by tool.name or filename.',
      supportedExports: [
        'export default async function(args, deps) {}',
        'export const tool = { name, description, inputSchema, call: async (args, deps) => {} }'
      ],
      injectedDeps: ['Utils', 'VFS', 'readFile', 'writeFile', 'loadModule'],
      note: 'Relative imports are not rewritten.'
    },
    toolCallProtocol: {
      responseFormat: 'Reply with exactly one JSON object.',
      singleToolCall: {
        tool: 'ReadFile',
        args: { path: '/.system/self.json' }
      },
      toolBatch: {
        tools: [
          { tool: 'ReadFile', args: { path: '/.system/self.json' } },
          { tool: 'ReadFile', args: { path: '/.system/goal.txt' } }
        ],
        batchLimit: 5,
        batchExecution: 'Batched tool calls run in order within one model cycle.'
      },
      milestone: {
        done: true,
        reason: '...'
      },
      notes: [
        'Milestones use the exact top-level object {"done": true, "reason": "..."}',
        'Do not nest a milestone inside {"done": {"done": true, "reason": "..."}}'
      ],
      stopCondition: 'The loop continues until you stop it, generation fails, or the cycle limit is reached. Plain text is recorded and ignored.'
    },
    readFirst: [
      '/.system/goal.txt',
      '/.system/environment.txt',
      '/.system/self.json'
    ]
  };
}

export function buildAbsoluteZeroSystemFiles(options = {}) {
  const goal = String(options.goal || '');
  const environment = String(options.environment || '').trim() || getDefaultAbsoluteZeroEnvironment();
  const includeHostWithinSelf = !!options.includeHostWithinSelf;
  return {
    '/.system/goal.txt': goal,
    '/.system/environment.txt': environment,
    '/.system/self.json': JSON.stringify(
      buildAbsoluteZeroSelfManifest({ includeHostWithinSelf }),
      null,
      2
    )
  };
}

export function listAbsoluteZeroSeedPaths(options = {}) {
  const includeHostWithinSelf = !!options.includeHostWithinSelf;
  const paths = new Set(Object.keys(buildAbsoluteZeroSystemFiles(options)));

  ABSOLUTE_ZERO_SELF_SOURCE_MIRRORS.forEach(({ vfsPath }) => paths.add(vfsPath));
  if (includeHostWithinSelf) {
    ABSOLUTE_ZERO_HOST_SOURCE_MIRRORS.forEach(({ vfsPath }) => paths.add(vfsPath));
  }

  return Array.from(paths).sort();
}
