export const DEFAULT_SPEC = {
  rounds: 16,
  vectors: 32,
  vlen: 8,
  depth4_rounds: 1,
  x4: 15,
  x5: 0,
  flow_setup: 64,
  reset_on_valu: true,
  shifts_on_valu: true,
  offload_op1: 0,
  offload_hash_op1: true,
  offload_hash_shift: false,
  offload_hash_op2: false,
  offload_parity: false,
  offload_node_xor: false,
  use_bitmask_selection: false,
  selection_mode: 'eq',
  selection_mode_by_round: {},
  valu_select: false,
  node_ptr_incremental: false,
  idx_shifted: false,
  use_temp_deps: true,
  ptr_setup_engine: 'flow',
  setup_style: 'inline',
  include_setup: true,
  proof_assume_shifted_input: false,
  proof_reset_single_op: false,
  proof_skip_const_zero: false,
  valu_pad_cycles: 0,
  vector_block: 32,
  extra_vecs: 2,
  cached_nodes: null,
  base_cached_rounds: [0, 1, 2, 3, 11, 12, 13, 14],
  depth4_cached_rounds: [4],
  cached_round_aliases: {},
  cached_round_depth: {},
  cached_round_x: {},
  valu_cap: 6,
  alu_cap: 12,
  flow_cap: 1,
  load_cap: 2,
  store_cap: 2,
  total_cycles: 1312,
  sched_seed: 0,
  sched_jitter: 0,
  sched_restarts: 1,
};

export const DEFAULT_DEPENDENCY_MODEL = {
  includes_raw: true,
  includes_waw: true,
  includes_war: true,
  temp_hazard_tags: true,
  read_after_read: false,
  latency: {
    default: 1,
    raw: 1,
    waw: 1,
    war: 0,
    temp: 1,
  },
};
