// Genesis Factory - Creates immutable recovery substrate
// Run this once via tool to generate your lifeboat

const GenesisFactory = {
  metadata: {
    id: 'GenesisFactory',
    version: '1.0.0',
    description: 'Freezes current substrate modules into immutable recovery kernel',
    dependencies: ['vfs'],
    type: 'system'
  },

  factory: (deps) => {
    const { vfs } = deps;

    const freezeKernel = async () => {
      // The critical path modules required to boot the UI and VFS
      const corePaths = [
        '/core/vfs.js',
        '/core/utils.js',
        '/infrastructure/event-bus.js',
        '/core/state-manager.js',
        '/core/response-parser.js',
        '/core/context-manager.js',
        '/core/llm-client.js',
        '/core/agent-loop.js',
        '/core/tool-runner.js'
      ];

      const kernel = {};
      let missing = [];

      for (const path of corePaths) {
        try {
          kernel[path] = await vfs.read(path);
        } catch (e) {
          missing.push(path);
        }
      }

      if (missing.length > 0) {
        throw new Error(`Cannot freeze kernel. Missing modules: ${missing.join(', ')}`);
      }

      const fileContent = `// GENESIS KERNEL - IMMUTABLE RECOVERY SUBSTRATE
// Generated: ${new Date().toISOString()}
// DO NOT EDIT THIS FILE. IT IS YOUR LIFEBOAT.

export const GENESIS_MODULES = ${JSON.stringify(kernel, null, 2)};
`;

      await vfs.write('/core/genesis-kernel.js', fileContent);
      return { success: true, message: "Genesis Kernel frozen. Safe Mode available." };
    };

    return { freezeKernel };
  }
};

export default GenesisFactory;
