#!/usr/bin/env node
/**
 * Validate recursive CATSCAN component charters and the generated index.
 */

import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const SCRIPT_PATH = fileURLToPath(import.meta.url);
export const PROJECT_ROOT = path.resolve(path.dirname(SCRIPT_PATH), '..');
export const COMPONENT_INDEX_PATH = path.join(PROJECT_ROOT, 'docs', 'component-index.md');
export const MAX_CATSCAN_WORDS = 250;

const REQUIRED_FIELDS = Object.freeze([
  'Parent',
  'Target',
  'Authority',
  'Scope',
  'Contracts',
  'Invariants',
  'Acceptance',
  'Non-goals',
  'Freedom'
]);

const IGNORED_DIRECTORIES = new Set([
  '.git',
  'node_modules',
  'playwright-report',
  'test-results',
  'coverage'
]);

const normalizeRelative = (root, filePath) => path.relative(root, filePath).split(path.sep).join('/');
const wordCount = (source) => source.trim() ? source.trim().split(/\s+/).length : 0;

const extractLocalLinks = (source) => [...source.matchAll(/\[[^\]]+\]\(([^)]+)\)/g)]
  .map((match) => match[1].trim())
  .filter((target) => target && !/^(?:[a-z]+:|#)/i.test(target));

const linkPath = (target) => {
  const withoutAnchor = target.split('#', 1)[0].split('?', 1)[0];
  try {
    return decodeURIComponent(withoutAnchor);
  } catch {
    return withoutAnchor;
  }
};

export function parseCatscan(source, { filePath = 'CATSCAN.md' } = {}) {
  const lines = String(source || '').replace(/\r\n/g, '\n').split('\n');
  const titleMatch = lines[0]?.match(/^# CATSCAN: (.+)$/);
  const fields = Object.create(null);
  let activeField = null;

  for (const line of lines.slice(1)) {
    if (line === 'Parent:' || line.startsWith('Parent: ')) {
      fields.Parent = line.slice('Parent:'.length).trim();
      activeField = null;
      continue;
    }
    const sectionMatch = line.match(/^## (Target|Authority|Scope|Contracts|Invariants|Acceptance|Non-goals|Freedom)$/);
    const marker = sectionMatch?.[1] || null;
    if (marker) {
      activeField = marker;
      fields[marker] = '';
      continue;
    }
    if (activeField) {
      fields[activeField] = `${fields[activeField]}\n${line}`.trim();
    }
  }

  return {
    filePath,
    component: titleMatch?.[1]?.trim() || '',
    fields,
    links: extractLocalLinks(source),
    words: wordCount(source)
  };
}

async function findCatscanFiles(root) {
  const found = [];
  const visit = async (directory) => {
    const entries = await fs.readdir(directory, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.isDirectory() && IGNORED_DIRECTORIES.has(entry.name)) continue;
      const resolved = path.join(directory, entry.name);
      if (entry.isDirectory()) await visit(resolved);
      else if (entry.isFile() && entry.name === 'CATSCAN.md') found.push(resolved);
    }
  };
  await visit(root);
  return found.sort((left, right) => normalizeRelative(root, left).localeCompare(normalizeRelative(root, right)));
}

const nearestParentCatscan = (filePath, root, catscanPaths) => {
  const candidates = new Set(catscanPaths.map((candidate) => path.resolve(candidate)));
  let directory = path.dirname(path.dirname(filePath));
  const resolvedRoot = path.resolve(root);
  while (directory === resolvedRoot || directory.startsWith(`${resolvedRoot}${path.sep}`)) {
    const candidate = path.join(directory, 'CATSCAN.md');
    if (candidates.has(candidate)) return candidate;
    if (directory === resolvedRoot) break;
    directory = path.dirname(directory);
  }
  return null;
};

const parentLinkTarget = (value) => {
  const match = String(value || '').match(/^\[[^\]]+\]\(([^)]+)\)$/);
  return match?.[1] || null;
};

const escapeTable = (value) => String(value || '').replace(/\|/g, '\\|').replace(/\s+/g, ' ').trim();

export function renderComponentIndex(charters, { root = PROJECT_ROOT } = {}) {
  const byPath = new Map(charters.map((charter) => [path.resolve(charter.filePath), charter]));
  const rows = [...charters].sort((left, right) => {
    const leftPath = normalizeRelative(root, left.filePath);
    const rightPath = normalizeRelative(root, right.filePath);
    if (leftPath === 'CATSCAN.md') return -1;
    if (rightPath === 'CATSCAN.md') return 1;
    const depthDifference = leftPath.split('/').length - rightPath.split('/').length;
    if (depthDifference !== 0) return depthDifference;
    return leftPath.localeCompare(rightPath);
  });
  const lines = [
    '<!-- Generated by scripts/verify-catscan.js --write. Do not edit directly. -->',
    '# Reploid Component Index',
    '',
    'Recursive authority charters discovered from the repository root.',
    '',
    '| Component | Charter | Parent | Target |',
    '| --- | --- | --- | --- |'
  ];

  for (const charter of rows) {
    const relative = normalizeRelative(root, charter.filePath);
    const linkFromIndex = path.relative(path.join(root, 'docs'), charter.filePath).split(path.sep).join('/');
    const parentTarget = parentLinkTarget(charter.fields.Parent);
    const parentPath = parentTarget
      ? path.resolve(path.dirname(charter.filePath), linkPath(parentTarget))
      : null;
    const parent = parentPath ? byPath.get(parentPath)?.component || 'Invalid parent' : 'None';
    lines.push(`| ${escapeTable(charter.component)} | [\`${relative}\`](${linkFromIndex}) | ${escapeTable(parent)} | ${escapeTable(charter.fields.Target)} |`);
  }

  lines.push('', '*Generated from CATSCAN.md files.*', '');
  return lines.join('\n');
}

export async function loadCatscans(root = PROJECT_ROOT) {
  const files = await findCatscanFiles(root);
  return Promise.all(files.map(async (filePath) => parseCatscan(
    await fs.readFile(filePath, 'utf8'),
    { filePath }
  )));
}

export async function validateCatscanRepository({
  root = PROJECT_ROOT,
  indexPath = path.join(root, 'docs', 'component-index.md'),
  checkIndex = true,
  maxWords = MAX_CATSCAN_WORDS
} = {}) {
  const errors = [];
  const charters = await loadCatscans(root);
  const catscanPaths = charters.map((charter) => path.resolve(charter.filePath));
  const rootCatscan = path.join(path.resolve(root), 'CATSCAN.md');

  if (!catscanPaths.includes(rootCatscan)) errors.push('repository root is missing CATSCAN.md');

  const seenComponents = new Map();
  for (const charter of charters) {
    const relative = normalizeRelative(root, charter.filePath);
    if (!charter.component) errors.push(`${relative}: first line must be # CATSCAN: <Component>`);
    const componentKey = charter.component.toLowerCase();
    if (componentKey && seenComponents.has(componentKey)) {
      errors.push(`${relative}: component identifier duplicates ${seenComponents.get(componentKey)}`);
    } else if (componentKey) {
      seenComponents.set(componentKey, relative);
    }

    for (const field of REQUIRED_FIELDS) {
      if (!String(charter.fields[field] || '').trim()) errors.push(`${relative}: missing ${field} field`);
    }
    if (charter.words > maxWords) {
      errors.push(`${relative}: ${charter.words} words exceeds the ${maxWords}-word charter limit`);
    }

    const isRoot = path.resolve(charter.filePath) === rootCatscan;
    if (isRoot) {
      if (String(charter.fields.Parent || '').toLowerCase() !== 'none') {
        errors.push(`${relative}: root Parent must be none`);
      }
    } else {
      const target = parentLinkTarget(charter.fields.Parent);
      if (!target) {
        errors.push(`${relative}: Parent must be one Markdown link`);
      } else {
        const actualParent = path.resolve(path.dirname(charter.filePath), linkPath(target));
        const expectedParent = nearestParentCatscan(charter.filePath, root, catscanPaths);
        if (actualParent !== expectedParent) {
          errors.push(`${relative}: Parent must reference ${normalizeRelative(root, expectedParent || rootCatscan)}`);
        }
      }
    }

    const acceptanceLinks = extractLocalLinks(charter.fields.Acceptance || '');
    if (!/(?:^|\n)\s*-?\s*Evidence:/m.test(charter.fields.Acceptance || '') || acceptanceLinks.length === 0) {
      errors.push(`${relative}: Acceptance must include an Evidence: link`);
    }

    if (!/(?:^|\n)Inputs:/m.test(charter.fields.Contracts || '')
      || !/(?:^|\n)Outputs:/m.test(charter.fields.Contracts || '')) {
      errors.push(`${relative}: Contracts must name Inputs and Outputs`);
    }

    for (const target of charter.links) {
      const targetPath = path.resolve(path.dirname(charter.filePath), linkPath(target));
      const resolvedRoot = path.resolve(root);
      if (!(targetPath === resolvedRoot || targetPath.startsWith(`${resolvedRoot}${path.sep}`))) {
        errors.push(`${relative}: local link escapes the repository: ${target}`);
        continue;
      }
      try {
        await fs.access(targetPath);
      } catch {
        errors.push(`${relative}: local link is missing: ${target}`);
      }
    }
  }

  if (checkIndex) {
    const expected = renderComponentIndex(charters, { root });
    let current = null;
    try {
      current = await fs.readFile(indexPath, 'utf8');
    } catch {
      errors.push(`${normalizeRelative(root, indexPath)}: generated component index is missing`);
    }
    if (current !== null && current !== expected) {
      errors.push(`${normalizeRelative(root, indexPath)}: generated component index is stale; run npm run build:component-index`);
    }
  }

  return { charters, errors };
}

export function catscanChainForPath(targetPath, charters, { root = PROJECT_ROOT } = {}) {
  const resolvedTarget = path.resolve(root, targetPath);
  return charters
    .filter((charter) => {
      const directory = path.dirname(path.resolve(charter.filePath));
      return resolvedTarget === directory || resolvedTarget.startsWith(`${directory}${path.sep}`);
    })
    .sort((left, right) => path.dirname(left.filePath).split(path.sep).length - path.dirname(right.filePath).split(path.sep).length);
}

export async function writeComponentIndex({
  root = PROJECT_ROOT,
  indexPath = path.join(root, 'docs', 'component-index.md')
} = {}) {
  const charters = await loadCatscans(root);
  const content = renderComponentIndex(charters, { root });
  await fs.writeFile(indexPath, content);
  return { charters, indexPath, content };
}

async function main() {
  const chainIndex = process.argv.indexOf('--chain');
  if (chainIndex >= 0) {
    const target = process.argv[chainIndex + 1];
    if (!target) throw new Error('--chain requires a repository-relative path');
    const charters = await loadCatscans();
    for (const charter of catscanChainForPath(target, charters)) {
      console.log(normalizeRelative(PROJECT_ROOT, charter.filePath));
    }
    return;
  }

  if (process.argv.includes('--write')) await writeComponentIndex();
  const { charters, errors } = await validateCatscanRepository();
  if (errors.length > 0) {
    console.error('[catscan] Errors:');
    for (const error of errors) console.error(`- ${error}`);
    process.exitCode = 1;
    return;
  }
  console.log(`[catscan] ${charters.length} component charters and generated index passed`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === SCRIPT_PATH) {
  main().catch((error) => {
    console.error('[catscan] Validation failed');
    console.error(error);
    process.exit(1);
  });
}
